from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import subprocess
import sys
import os

app = FastAPI(title="TeamClubAI Backend Router")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_methods=["*"],
    allow_headers=["*"],
)

class PythonPayload(BaseModel):
    code: str

@app.post("/execute-tunnel")
async def execute_tunnel(payload: PythonPayload):
    """Executes code generated by the Coder Agent."""
    try:
        with open("temp_worker.py", "w") as f:
            f.write(payload.code)

        result = subprocess.run(
            [sys.executable, "temp_worker.py"],
            capture_output=True,
            text=True,
            timeout=15 # Prevents infinite loops locking the server
        )
        
        if os.path.exists("temp_worker.py"):
            os.remove("temp_worker.py")

        return {
            "stdout": result.stdout,
            "stderr": result.stderr,
            "status": "success" if result.returncode == 0 else "error"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
